#!/usr/bin/env python3

import numpy as np
import json
import os
import sys

def export_case(meta_path, npz_path, case_name, expression_idx=2):

    with open(meta_path) as f:
        meta = json.load(f)

    data = np.load(npz_path)

    q = meta["q"]
    challenges = meta["challenges"]
    num_vars = meta.get("num_vars", len(challenges))
    expr_data = meta["expected"][expression_idx]
    expression = expr_data["expression"]
    round_evals = expr_data["round_evals"]

    table_size = 2 ** num_vars

    lines = []
    lines.append(f"// ── Test case: {case_name} ──")
    lines.append(f"// Expression: {' + '.join('*'.join(t) for t in expression)}")
    lines.append(f"// q = {q}, num_vars = {num_vars}, table_size = {table_size}")
    lines.append(f"")
    lines.append(f"#define {case_name.upper()}_Q           {q}u")
    lines.append(f"#define {case_name.upper()}_NUM_VARS     {num_vars}")
    lines.append(f"#define {case_name.upper()}_TABLE_SIZE   {table_size}")
    lines.append(f"#define {case_name.upper()}_NUM_ROUNDS   {num_vars}")
    lines.append(f"#define {case_name.upper()}_DEGREE       {max(len(t) for t in expression)}")
    lines.append(f"#define {case_name.upper()}_NUM_TERMS    {len(expression)}")
    lines.append(f"")

    lines.append(f"static const uint32_t {case_name}_challenges[{num_vars}] = {{")
    lines.append(f"    {', '.join(str(c) + 'u' for c in challenges)}")
    lines.append(f"}};")
    lines.append(f"")

    for var_name in ["a", "b", "c", "d", "e", "g"]:
        arr = data[var_name].astype(np.uint64)
        arr_mod = [int(v) % q for v in arr]
        lines.append(f"static const uint32_t {case_name}_table_{var_name}[{table_size}] = {{")
        for i in range(0, len(arr_mod), 4):
            chunk = arr_mod[i:i+4]
            line = "    " + ", ".join(f"{v}u" for v in chunk)
            if i + 4 < len(arr_mod):
                line += ","
            lines.append(line)
        lines.append(f"}};")
        lines.append(f"")

    degree = max(len(t) for t in expression)
    num_evals = degree + 1
    lines.append(f"static const uint32_t {case_name}_expected[{num_vars}][{num_evals}] = {{")
    for r, evals in enumerate(round_evals):
        vals = ", ".join(f"{int(v) % q}u" for v in evals)
        comma = "," if r < len(round_evals) - 1 else ""
        lines.append(f"    {{ {vals} }}{comma}  // round {r}")
    lines.append(f"}};")
    lines.append(f"")

    return "\n".join(lines)


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))

    for candidate in [
        os.path.join(script_dir, "..", "..", "ECE-9413", "assignment2"),
        os.path.join(script_dir, "..", "ECE-9413", "assignment2"),
        ".",
    ]:
        test_dir = os.path.join(candidate, "tests", "data", "vars4")
        if os.path.exists(test_dir):
            break
    else:
        print("ERROR: Could not find tests/data/vars4 directory.")
        print("       Run this script from the assignment2 directory.")
        sys.exit(1)

    header = []
    header.append("// test_vectors.h — Auto-generated from assignment2 test data")
    header.append("// Generated by export_test_vectors.py")
    header.append("")
    header.append("#ifndef TEST_VECTORS_H")
    header.append("#define TEST_VECTORS_H")
    header.append("")
    header.append("#include <stdint.h>")
    header.append("")

    meta_path = os.path.join(test_dir, "v4_case32_0_meta.json")
    npz_path = os.path.join(test_dir, "v4_case32_0.npz")

    if os.path.exists(meta_path) and os.path.exists(npz_path):
        header.append(export_case(meta_path, npz_path, "v4_case32_0", expression_idx=2))
    else:
        print(f"WARNING: {meta_path} or {npz_path} not found, skipping")

    header.append("#endif // TEST_VECTORS_H")

    out_path = os.path.join(script_dir, "..", "hls_src", "test_vectors.h")
    with open(out_path, "w") as f:
        f.write("\n".join(header) + "\n")

    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
